name: LocalStack Workflow

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: LocalStack Preview
        uses: LocalStack/setup-localstack@v0.2.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          state-backend: ephemeral
          state-action: start
          include-preview: "true"
          install-awslocal: "true"
          preview-cmd: |
            pip install terraform-local
            pnpm install
            pnpm --filter react build
            pnpm --filter server build
            zip -r ./terraform/preview/lambda.zip ./apps/server/.output/server
            cd ./terraform/preview
            ls && pwd
            tflocal init
            tflocal apply --auto-approve
        env:
          LOCALSTACK_API_KEY: ${{ secrets.LOCALSTACK_API_KEY }}
